const sideBarElements = [
    {
      id: 1,
      link: "/dashboard",
      label: "Dashboard",
    },
    {
      id: 2,
      link: "/employees",
      label: "Employees",
    },
    {
      id: 3,
      link: "/organization-tree",
      label: "Organization Tree",
    },
  ];

const topPerformers = [
    { name: "John Doe", position: "Software Engineer", imageUrl: "https://randomuser.me/api/portraits/men/5.jpg" },
    { name: "Jane Smith", position: "Product Manager", imageUrl: "https://randomuser.me/api/portraits/women/4.jpg" },
    { name: "Alice Johnson", position: "UI/UX Designer", imageUrl: "https://randomuser.me/api/portraits/women/2.jpg" },
    { name: "Bob Brown", position: "DevOps Engineer", imageUrl: "https://randomuser.me/api/portraits/women/4.jpg" },
];
const bestTeam = {
    name: "Alpha Squad",
    description: "Crushed all goals this month with outstanding teamwork!",
    members: [
      { name: "Mark Lee", imageUrl: "https://randomuser.me/api/portraits/men/10.jpg" },
      { name: "Sara Connor", imageUrl: "https://randomuser.me/api/portraits/women/12.jpg" },
      { name: "Tom Hardy", imageUrl: "https://randomuser.me/api/portraits/men/15.jpg" },
    ],
  };
  
const upcomingEvents = [
    { name: "Laura Palmer", date: "13 Aug", type: "birthday" },
    { name: "Peter Parker", date: "14 Aug", type: "anniversary" },
    { name: "Bruce Wayne", date: "15 Aug", type: "birthday" },
  ];

const employees = [
    {
      id: 1,
      name: "Leanne Graham",
      username: "Bret",
      email: "Sincere@april.biz",
      photo: "https://randomuser.me/api/portraits/men/9.jpg",
      role: "Software Engineer",
      department: "Engineering",
      level: "0",
      managerId: null,
    },
    {
      id: 2,
      name: "Ervin Howell",
      username: "Antonette",
      email: "Shanna@melissa.tv",
      photo: "https://randomuser.me/api/portraits/women/14.jpg",
      role: "Product Manager",
      department: "Engineering",
      level: "1",
      managerId: 1,
    },
    {
      id: 3,
      name: "Clementine Bauch",
      username: "Samantha",
      email: "Nathan@yesenia.net",
      photo: "https://randomuser.me/api/portraits/men/27.jpg",
      role: "Team Lead",
      department: "Engineering",
      level: "2",
      managerId: 2,
    },
    {
      id: 4,
      name: "Patricia Lebsack",
      username: "Karianne",
      email: "Julianne.OConner@kory.org",
      photo: "https://randomuser.me/api/portraits/women/28.jpg",
      role: "QA Engineer",
      department: "Quality Assurance",
      level: "1",
      managerId: 20,
    },
    {
      id: 5,
      name: "Chelsey Dietrich",
      username: "Kamren",
      email: "Lucio_Hettinger@annie.ca",
      photo: "https://randomuser.me/api/portraits/men/45.jpg",
      role: "Data Analyst",
      department: "Engineering",
      level: "1",
      managerId: 24,
    },
    {
      id: 6,
      name: "Mrs. Dennis Schulist",
      username: "Leopoldo_Corkery",
      email: "Karley_Dach@jasper.info",
      photo: "https://randomuser.me/api/portraits/women/42.jpg",
      role: "HR Manager",
      department: "Human Resources",
      level: "1",
      managerId: 1,
    },
    {
      id: 7,
      name: "Kurtis Weissnat",
      username: "Elwyn.Skiles",
      email: "Telly.Hoeger@billy.biz",
      photo: "https://randomuser.me/api/portraits/men/63.jpg",
      role: "DevOps Engineer",
      department: "DevOps",
      level: "2",
      managerId: 22,
    },
    {
      id: 8,
      name: "Nicholas Runolfsdottir V",
      username: "Maxime_Nienow",
      email: "Sherwood@rosamond.me",
      photo: "https://randomuser.me/api/portraits/women/56.jpg",
      role: "Marketing Specialist",
      department: "Sales",
      level: "2",
      managerId: 1,
    },
    {
      id: 9,
      name: "Glenna Reichert",
      username: "Delphine",
      email: "Chaim_McDermott@dana.io",
      photo: "https://randomuser.me/api/portraits/men/81.jpg",
      role: "Business Analyst",
      department: "Engineering",
      level: "2",
      managerId: 5,
    },
    {
      id: 10,
      name: "Clementina DuBuque",
      username: "Moriah.Stanton",
      email: "Rey.Padberg@karina.biz",
      photo: "https://randomuser.me/api/portraits/women/70.jpg",
      role: "Customer Success Manager",
      department: "Sales",
      level: "3",
      managerId: 8,
    },
    // New entries added below (11 - 25)
    {
      id: 11,
      name: "John Doe",
      username: "john.doe",
      email: "john.doe@example.com",
      photo: "https://randomuser.me/api/portraits/men/10.jpg",
      role: "Frontend Developer",
      department: "Engineering",
      level: "2",
      managerId: 3,
    },
    {
      id: 12,
      name: "Jane Smith",
      username: "jane.smith",
      email: "jane.smith@example.com",
      photo: "https://randomuser.me/api/portraits/women/22.jpg",
      role: "Backend Developer",
      department: "Engineering",
      level: "2",
      managerId: 3,
    },
    {
      id: 13,
      name: "Alice Johnson",
      username: "alice.johnson",
      email: "alice.johnson@example.com",
      photo: "https://randomuser.me/api/portraits/women/31.jpg",
      role: "QA Tester",
      department: "Quality Assurance",
      level: "2",
      managerId: 20,
    },
    {
      id: 14,
      name: "Bob Williams",
      username: "bob.williams",
      email: "bob.williams@example.com",
      photo: "https://randomuser.me/api/portraits/men/41.jpg",
      role: "Recruiter",
      department: "Human Resources",
      level: "2",
      managerId: 6,
    },
    {
      id: 15,
      name: "Charlie Brown",
      username: "charlie.brown",
      email: "charlie.brown@example.com",
      photo: "https://randomuser.me/api/portraits/men/55.jpg",
      role: "DevOps Specialist",
      department: "DevOps",
      level: "3",
      managerId: 22,
    },
    {
      id: 16,
      name: "Dorothy Gale",
      username: "dorothy.gale",
      email: "dorothy.gale@example.com",
      photo: "https://randomuser.me/api/portraits/women/60.jpg",
      role: "Sales Executive",
      department: "Sales",
      level: "3",
      managerId: 10,
    },
    {
      id: 17,
      name: "Eve Adams",
      username: "eve.adams",
      email: "eve.adams@example.com",
      photo: "https://randomuser.me/api/portraits/women/72.jpg",
      role: "HR Assistant",
      department: "Human Resources",
      level: "2",
      managerId: 6,
    },
    {
      id: 18,
      name: "Frank Miller",
      username: "frank.miller",
      email: "frank.miller@example.com",
      photo: "https://randomuser.me/api/portraits/men/75.jpg",
      role: "Engineering Intern",
      department: "Engineering",
      level: "3",
      managerId: 12,
    },
    {
      id: 19,
      name: "Grace Lee",
      username: "grace.lee",
      email: "grace.lee@example.com",
      photo: "https://randomuser.me/api/portraits/women/80.jpg",
      role: "UX Researcher",
      department: "Engineering",
      level: "2",
      managerId: 3,
    },
    {
      id: 20,
      name: "Henry Clark",
      username: "henry.clark",
      email: "henry.clark@example.com",
      photo: "https://randomuser.me/api/portraits/men/88.jpg",
      role: "Quality Assurance Lead",
      department: "Quality Assurance",
      level: "2",
      managerId: 1,
    },
    {
      id: 21,
      name: "Ivy Martinez",
      username: "ivy.martinez",
      email: "ivy.martinez@example.com",
      photo: "https://randomuser.me/api/portraits/women/90.jpg",
      role: "Marketing Manager",
      department: "Sales",
      level: "2",
      managerId: 8,
    },
    {
      id: 22,
      name: "Jack Wilson",
      username: "jack.wilson",
      email: "jack.wilson@example.com",
      photo: "https://randomuser.me/api/portraits/men/92.jpg",
      role: "DevOps Manager",
      department: "DevOps",
      level: "3",
      managerId: 2,
    },
    {
      id: 23,
      name: "Kelly Green",
      username: "kelly.green",
      email: "kelly.green@example.com",
      photo: "https://randomuser.me/api/portraits/women/95.jpg",
      role: "HR Coordinator",
      department: "Human Resources",
      level: "2",
      managerId: 6,
    },
    {
      id: 24,
      name: "Larry King",
      username: "larry.king",
      email: "larry.king@example.com",
      photo: "https://randomuser.me/api/portraits/men/97.jpg",
      role: "Business Intelligence Analyst",
      department: "Engineering",
      level: "3",
      managerId: 1,
    },
    {
      id: 25,
      name: "Mona Scott",
      username: "mona.scott",
      email: "mona.scott@example.com",
      photo: "https://randomuser.me/api/portraits/women/99.jpg",
      role: "Sales Support Specialist",
      department: "Sales",
      level: "3",
      managerId: 10,
    },
  ];
  
  
   
  
export { sideBarElements, topPerformers, bestTeam, upcomingEvents, employees };