export const adminChildren = {
    id: "1",
    email: "orginsight@orginsight.com",
    username: "orginsight",
    emailVerified: true,
    isActive: true,
    adminRoleId: "1",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    children: [
      {
        id: "59",
        email: "user59.random@gmail.com",
        username: "saddsdssd",
        lastName: "dffdfdfd",
        firstName: "sdds",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "3",
        photo: "https://randomuser.me/api/portraits/men/59.jpg"
      },
      {
        id: "61",
        email: "user61.random@gmail.com",
        username: "krishnat",
        lastName: "karn",
        firstName: "krishna",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/61.jpg"
      },
      {
        id: "48",
        email: "user48.random@gmail.com",
        username: "Staffmanager",
        lastName: "manager",
        firstName: "Staff",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/48.jpg",
        children: [
          {
            id: "49",
            email: "user49.random@gmail.com",
            username: "managerapp",
            lastName: "manager",
            firstName: "app",
            emailVerified: true,
            parentAdminId: "48",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/women/49.jpg"
          },
          {
            id: "64",
            email: "user64.random@gmail.com",
            username: "Domai23423",
            lastName: "Domain",
            firstName: "Domain",
            emailVerified: true,
            parentAdminId: "48",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/men/64.jpg"
          },
        ],
      },
      {
        id: "53",
        email: "user53.random@gmail.com",
        username: "randyortan",
        lastName: "orton",
        firstName: "randy",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/53.jpg"
      },
      {
        id: "56",
        email: "user56.random@gmail.com",
        username: "rohithkumar",
        lastName: "Kumar",
        firstName: "Rohith",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "3",
        photo: "https://randomuser.me/api/portraits/men/56.jpg"
      },
      {
        id: "5",
        email: "user5.random@gmail.com",
        username: "chethankumar",
        lastName: "kumar",
        firstName: "chethan",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/5.jpg",
        children: [
          {
            id: "51",
            email: "user51.random@gmail.com",
            username: "chethanclone",
            lastName: "clone",
            firstName: "chethan",
            emailVerified: true,
            parentAdminId: "5",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/women/51.jpg"
          },
        ],
      },
      {
        id: "60",
        email: "user60.random@gmail.com",
        username: "Rohithallam",
        lastName: "Allam",
        firstName: "Rohith",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/60.jpg"
      },
      {
        id: "22",
        email: "user22.random@gmail.com",
        username: "wildcraft",
        lastName: "kumar",
        firstName: "wildcraft",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/22.jpg"
      },
      {
        id: "62",
        email: "user62.random@gmail.com",
        username: "shubhamthree",
        lastName: "kumawat",
        firstName: "shubham",
        emailVerified: true,
        parentAdminId: "1",
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/62.jpg"
      },
      {
        id: "54",
        email: "user54.random@gmail.com",
        username: "rohithjjksjdf",
        lastName: "fdfdffvvf",
        firstName: "aaafdgh",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "3",
        photo: "https://randomuser.me/api/portraits/women/54.jpg"
      },
      {
        id: "57",
        email: "user57.random@gmail.com",
        username: "chrisgayle ",
        lastName: "gayle",
        firstName: "chris",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/57.jpg"
      },
      {
        id: "65",
        email: "user65.random@gmail.com",
        username: "vineethkhan",
        lastName: "Khan",
        firstName: "Vineeth",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/65.jpg",
        children: [
          {
            id: "66",
            email: "user66.random@gmail.com",
            username: "Saikiran",
            lastName: "Kiran",
            firstName: "Saiiii",
            emailVerified: true,
            parentAdminId: "65",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/men/66.jpg"
          },
        ],
      },
      {
        id: "30",
        email: "user30.random@gmail.com",
        username: "shubhamtwo",
        lastName: "kumawat",
        firstName: "shubh",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/30.jpg",
        children: [
          {
            id: "52",
            email: "user52.random@gmail.com",
            username: "staffKrishna",
            lastName: "Staff",
            firstName: "Krishna",
            emailVerified: true,
            parentAdminId: "30",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/women/52.jpg"
          },
        ],
      },
      {
        id: "63",
        email: "user63.random@gmail.com",
        username: "Keshavardhan",
        lastName: "Vardhan",
        firstName: "Kesha ",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "3",
        photo: "https://randomuser.me/api/portraits/men/63.jpg"
      },
      {
        id: "55",
        email: "user55.random@gmail.com",
        username: "vijaykumar",
        lastName: "abcdef",
        firstName: "abcde",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "3",
        photo: "https://randomuser.me/api/portraits/men/55.jpg"
      },
      {
        id: "41",
        email: "user41.random@gmail.com",
        username: "TAgsuser",
        lastName: "Taguser",
        firstName: "TAguser",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/41.jpg"
      },
      {
        id: "43",
        email: "user43.random@gmail.com",
        username: "Segmentmanager",
        lastName: "manager",
        firstName: "Segment",
        emailVerified: true,
        parentAdminId: "1",
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/43.jpg"
      },
      {
        id: "42",
        email: "user42.random@gmail.com",
        username: "Bonusmanager",
        lastName: "manager",
        firstName: "Bonus",
        emailVerified: true,
        parentAdminId: "1",
        isActive: true,
        adminRoleId: "2",
        photo: "https://randomuser.me/api/portraits/men/42.jpg",
        children: [
          {
            id: "50",
            email: "user50.random@gmail.com",
            username: "chethananderson",
            lastName: "kumar",
            firstName: "chethan",
            emailVerified: true,
            parentAdminId: "42",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/women/50.jpg"
          },
          {
            id: "47",
            email: "user47.random@gmail.com",
            username: "Staffuserbonus",
            lastName: "Bonusstaffuser",
            firstName: "Staff userbonus",
            emailVerified: true,
            parentAdminId: "42",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/men/47.jpg"
          },
          {
            id: "44",
            email: "user44.random@gmail.com",
            username: "Bonusstaff",
            lastName: "staff",
            firstName: "Bonus",
            emailVerified: true,
            parentAdminId: "42",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/women/44.jpg"
          },
          {
            id: "45",
            email: "user45.random@gmail.com",
            username: "Staffbonus",
            lastName: "manager",
            firstName: "USerbonus",
            emailVerified: true,
            parentAdminId: "42",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/women/45.jpg"
          },
          {
            id: "58",
            email: "user58.random@gmail.com",
            username: "dhjdsjhsdfjlhsdfl",
            lastName: "bbbbbb",
            firstName: "aaaaaaa",
            emailVerified: true,
            parentAdminId: "42",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/men/58.jpg"
          },
          {
            id: "46",
            email: "user46.random@gmail.com",
            username: "Bonususerstaff",
            lastName: "userstaff",
            firstName: "Bonusstaffuser",
            emailVerified: true,
            parentAdminId: "42",
            isActive: true,
            adminRoleId: "3",
            photo: "https://randomuser.me/api/portraits/women/46.jpg"
          },
        ],
      },
    ],
  };
  