export const getEmployees = async () => {
    return [
      {
        id: 1,
        name: "Leanne Graham",
        username: "Bret",
        email: "Sincere@april.biz",
        photo: "https://randomuser.me/api/portraits/men/9.jpg",
        role: "Software Engineer",
        department: "Engineering", 
        managerId: null,
      },
      {
        id: 2,
        name: "Ervin Howell",
        username: "Antonette",
        email: "Shanna@melissa.tv",
        photo: "https://randomuser.me/api/portraits/women/14.jpg",
        role: "Product Manager",
        department: "Engineering",
        managerId: 1,
      },
      {
        id: 3,
        name: "Clementine Bauch",
        username: "Samantha",
        email: "Nathan@yesenia.net",
        photo: "https://randomuser.me/api/portraits/men/27.jpg",
        role: "UX Designer",
        department: "Engineering",
        managerId: 2,
      },
      {
        id: 4,
        name: "Patricia Lebsack",
        username: "Karianne",
        email: "Julianne.OConner@kory.org",
        photo: "https://randomuser.me/api/portraits/women/28.jpg",
        role: "QA Engineer",
        department: "Quality Assurance",
        managerId: 1,
      },
      {
        id: 5,
        name: "Chelsey Dietrich",
        username: "Kamren",
        email: "Lucio_Hettinger@annie.ca",
        photo: "https://randomuser.me/api/portraits/men/45.jpg",
        role: "Data Analyst",
        department: "Engineering",
        managerId: 1,
      },
      {
        id: 6,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        email: "Karley_Dach@jasper.info",
        photo: "https://randomuser.me/api/portraits/women/42.jpg",
        role: "HR Manager",
        department: "Human Resources",
        managerId: 1,
      },
      {
        id: 7,
        name: "Kurtis Weissnat",
        username: "Elwyn.Skiles",
        email: "Telly.Hoeger@billy.biz",
        photo: "https://randomuser.me/api/portraits/men/63.jpg",
        role: "DevOps Engineer",
        department: "DevOps",
        managerId: 2,
      },
      {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        email: "Sherwood@rosamond.me",
        photo: "https://randomuser.me/api/portraits/women/56.jpg",
        role: "Marketing Specialist",
        department: "Sales",
        managerId: 1,
      },
      {
        id: 9,
        name: "Glenna Reichert",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        photo: "https://randomuser.me/api/portraits/men/81.jpg",
        role: "Business Analyst",
        department: "Engineering",
        managerId: 5,
      },
      {
        id: 10,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        email: "Rey.Padberg@karina.biz",
        photo: "https://randomuser.me/api/portraits/women/70.jpg",
        role: "Customer Success Manager",
        department: "Sales",
        managerId: 8,
      },
    ];      
  };
  